#!/usr/bin/env bash
set -eo pipefail

{
  date
  bash -lc "
    exec alerterr \
      --name=qbtmindf --on_err='/(pausing|resuming) torrent/' -- \
      flock /tmp/qbtmindf_cronjob.lock \
        bundle exec ruby main.rb check_min \
          ~/windata \
          2048 M \
          'http://admin:adminqbit@winpc:8080'
  "
} 2>&1 | tee /tmp/qbtmindf_cronjob.log
